// Prisma File->Talks to database

// Import Prisma Client generated by Prisma
import { PrismaClient } from "@prisma/client";

// Create a single Prisma instance
const prisma = new PrismaClient();

// Export Prisma instance
export default prisma;
